version: "3.8"
services:
  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./database/data:/var/lib/mysql
  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database
    volumes:
      - ./src:/var/www:cached
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./src:/var/www:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"